Add Result.Unmarshal unmarshaling method
BooleanCat/go-functional pull request #80
Opened 2023-08-28 16:01 UTC by myusko

**Please provide a brief description of the change.**

Add the `Unmarshal` method to the **Result** struct.

**Which issue does this change relate to?**

https://github.com/BooleanCat/go-functional/issues/79

**Contribution checklist.**

- [X] I have read and understood the CONTRIBUTING guidelines
- [X] My code is formatted (`make check`)
- [X] I have run tests (`make test`)
- [X] All commits in my PR conform to the commit hygiene section
- [X] I have added relevant tests
- [X] I have not added any dependencies

**Additional context**

None

2023-08-28 16:08 UTC, BooleanCat requested changes
Thanks! Nice and simple implementation, I like it.

A few minor requests.

2023-08-28 16:08 UTC, BooleanCat commented on result/result_test.go
> +}
I'd prefer a simpler example output for the docs:

```go
fmt.Println(...)
// Output: Ok(...)
```

2023-08-28 16:08 UTC, BooleanCat commented on result/result_test.go
> +	_ = json.Unmarshal([]byte(`["Ford", "BMW", "Fiat"]`), &r)
Please avoid brand / company names in the code.

2023-08-28 16:08 UTC, BooleanCat commented on result/result.go
> +// UnmarshalJSON implements the [json.Unmarshaler] interface.
Do be consistent with option, please move the code and tests in `json.go` and `json_test.go` within the result package.

2023-08-28 19:28 UTC, myusko commented
> ## [Codecov](https://app.codecov.io/gh/BooleanCat/go-functional/pull/80?src=pr&el=h1&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Tom+Godkin) Report
> Patch coverage: **`62.50%`** and project coverage change: **`-0.57%`** ⚠️
> 
> > Comparison is base [(`83c7a18`)](https://app.codecov.io/gh/BooleanCat/go-functional/commit/83c7a184a8367665c27a5d433b3b4544d888bc36?el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Tom+Godkin) 100.00% compared to head [(`c76049f`)](https://app.codecov.io/gh/BooleanCat/go-functional/pull/80?src=pr&el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Tom+Godkin) 99.43%.
> 
> Additional details and impacted files
> [☔ View full report in Codecov by Sentry](https://app.codecov.io/gh/BooleanCat/go-functional/pull/80?src=pr&el=continue&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Tom+Godkin). 📢 Have feedback on the report? [Share it here](https://about.codecov.io/codecov-pr-comment-feedback/?utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Tom+Godkin).

Hehe 🙂 probably we need to add one more test that verifies that we are correctly returning an error, to make the codecov happy.

2023-08-28 19:49 UTC, BooleanCat commented
I think so - like this one: https://github.com/BooleanCat/go-functional/blob/83c7a184a8367665c27a5d433b3b4544d888bc36/option/json_test.go#L68

2023-08-28 20:23 UTC, BooleanCat commented
Oh one more optional (I'd merge without this), I use this trick to get a compile guarantee that an interface is implemented: https://github.com/BooleanCat/go-functional/blob/83c7a184a8367665c27a5d433b3b4544d888bc36/option/json.go#L37

2023-08-30 08:13 UTC, merged

2023-08-30 08:14 UTC, BooleanCat commented
Thanks for the contribution!